### ISSUE TITLE
这里只统计了最后一个 snapshot 的信息，是不是不准？基于什么考虑的呢？

### ISSUE THREAD

**Issue by Tryking** [kubackup/kubackup#4]
restic_proxy/restic_stats.go

stats, err := runStats(opts, repoi.repoId, []string{snres.ShortID})

这里只统计了最后一个 snapshot 的信息，是不是不准？基于什么考虑的呢？

**Comment by kubackup** [comment]
感谢反馈，将在下一个版本修复

**Comment by kubackup** [comment]
v1.2.3 修改了该问题，但是引发了另外一个问题，常驻内存会增加，数据量过大是应该谨慎考虑
